<?php
$value = array (
  'wwwprefix' => 'http://localhost',
  'imgprefix' => 'http://localhost',
  'cssprefix' => 'http://localhost',
  'sitename' => '大众食堂',
  'sitetitle' => '人是铁饭是钢，一顿不吃饿得慌。',
  'abbreviation' => '食堂',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'editor' => 'kind',
  'description' => '123123',
  'keywords' => '快餐，盒饭',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'indexteam' => '50',
  'sideteam' => '0',
);
?>