<?php
$value = array (
  'wwwprefix' => 'http://localhost',
  'imgprefix' => 'http://localhost',
  'cssprefix' => 'http://localhost',
  'sitename' => '还没想好',
  'sitetitle' => 'WAIT。。。',
  'abbreviation' => 'DEBUG',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'editor' => 'kind',
  'description' => '123123',
  'keywords' => 'dsfasdf',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'indexteam' => '50',
  'sideteam' => '0',
);
?>